In [2]:
import pandas as pd
import numpy as np

In [3]:
marks = np.random.randint(30, 100, (10,5))
print(marks)

[[98 60 88 54 72]
 [37 83 80 73 78]
 [31 62 87 69 46]
 [68 81 66 36 38]
 [36 75 72 30 59]
 [81 88 96 74 75]
 [71 59 95 95 53]
 [58 99 79 72 30]
 [68 53 82 33 50]
 [30 96 59 87 63]]


In [4]:
subjects = np.array(["English", "Physics", "Maths", "Biology", "Computer"])
result = pd.DataFrame(marks, columns=subjects, index=np.arange(1,11))
print(result)

    English  Physics  Maths  Biology  Computer
1        98       60     88       54        72
2        37       83     80       73        78
3        31       62     87       69        46
4        68       81     66       36        38
5        36       75     72       30        59
6        81       88     96       74        75
7        71       59     95       95        53
8        58       99     79       72        30
9        68       53     82       33        50
10       30       96     59       87        63


In [5]:
# Computing the total marks for each student
total_marks = np.sum(marks, axis=1)
print(total_marks)

[372 351 295 289 272 414 373 338 286 335]


In [6]:
result["Total"] = total_marks
print(result)

    English  Physics  Maths  Biology  Computer  Total
1        98       60     88       54        72    372
2        37       83     80       73        78    351
3        31       62     87       69        46    295
4        68       81     66       36        38    289
5        36       75     72       30        59    272
6        81       88     96       74        75    414
7        71       59     95       95        53    373
8        58       99     79       72        30    338
9        68       53     82       33        50    286
10       30       96     59       87        63    335


In [7]:
# Computing the mean of each subject
subject_mean = np.mean(marks, axis=0).reshape(1,5)
print(subject_mean)

[[57.8 75.6 80.4 62.3 56.4]]


In [9]:
# print(subject_mean[1])

In [10]:
print(np.sum(subject_mean))

332.49999999999994


In [11]:
# Assigning the mean row with index name 'Mean'
mean_row = pd.DataFrame(subject_mean, index=['Mean'], columns=subjects)
print(mean_row)
# mean_row = pd.DataFrame(
#     [{'English': subject_mean[0],
#       'Physics': subject_mean[1],
#       'Maths': subject_mean[2],
#       'Biology': subject_mean[3],
#       'Computer': subject_mean[4],
#       'Total': np.sum(subject_mean)}],
#     index=["Mean"]
# )

      English  Physics  Maths  Biology  Computer
Mean     57.8     75.6   80.4     62.3      56.4


In [12]:
# Using pd.concat to add the new row with custom index
final_result = pd.concat([result, mean_row])
print(final_result)

      English  Physics  Maths  Biology  Computer  Total
1        98.0     60.0   88.0     54.0      72.0  372.0
2        37.0     83.0   80.0     73.0      78.0  351.0
3        31.0     62.0   87.0     69.0      46.0  295.0
4        68.0     81.0   66.0     36.0      38.0  289.0
5        36.0     75.0   72.0     30.0      59.0  272.0
6        81.0     88.0   96.0     74.0      75.0  414.0
7        71.0     59.0   95.0     95.0      53.0  373.0
8        58.0     99.0   79.0     72.0      30.0  338.0
9        68.0     53.0   82.0     33.0      50.0  286.0
10       30.0     96.0   59.0     87.0      63.0  335.0
Mean     57.8     75.6   80.4     62.3      56.4    NaN


In [13]:
# final_result[final_result['Total'] == 'NaN'] = np.sum(subject_mean)
final_result = final_result.fillna(np.sum(subject_mean))
print(final_result)

      English  Physics  Maths  Biology  Computer  Total
1        98.0     60.0   88.0     54.0      72.0  372.0
2        37.0     83.0   80.0     73.0      78.0  351.0
3        31.0     62.0   87.0     69.0      46.0  295.0
4        68.0     81.0   66.0     36.0      38.0  289.0
5        36.0     75.0   72.0     30.0      59.0  272.0
6        81.0     88.0   96.0     74.0      75.0  414.0
7        71.0     59.0   95.0     95.0      53.0  373.0
8        58.0     99.0   79.0     72.0      30.0  338.0
9        68.0     53.0   82.0     33.0      50.0  286.0
10       30.0     96.0   59.0     87.0      63.0  335.0
Mean     57.8     75.6   80.4     62.3      56.4  332.5


In [14]:
high_achievers = result[result['Total'] >= 300]
print(high_achievers)

    English  Physics  Maths  Biology  Computer  Total
1        98       60     88       54        72    372
2        37       83     80       73        78    351
6        81       88     96       74        75    414
7        71       59     95       95        53    373
8        58       99     79       72        30    338
10       30       96     59       87        63    335
