In [4]:
import pandas as pd
import numpy as np

In [110]:
marks = np.random.randint(40, 100, (10,5))
print(marks)

[[56 58 92 98 65]
 [98 65 82 58 64]
 [50 96 57 69 59]
 [82 99 51 79 99]
 [81 85 83 82 57]
 [71 56 65 90 86]
 [95 44 94 47 62]
 [78 55 57 94 73]
 [41 63 95 63 79]
 [96 64 78 42 71]]


In [111]:
subjects = np.array(["English", "Physics", "Maths", "Biology", "Computer"])
result = pd.DataFrame(marks, columns=subjects, index=np.arange(1,11))
print(result)

    English  Physics  Maths  Biology  Computer
1        56       58     92       98        65
2        98       65     82       58        64
3        50       96     57       69        59
4        82       99     51       79        99
5        81       85     83       82        57
6        71       56     65       90        86
7        95       44     94       47        62
8        78       55     57       94        73
9        41       63     95       63        79
10       96       64     78       42        71


In [112]:
# Computing the total marks for each student
total_marks = np.sum(marks, axis=1)
print(total_marks)

[369 367 331 410 388 368 342 357 341 351]


In [113]:
result["Total"] = total_marks
print(result)

    English  Physics  Maths  Biology  Computer  Total
1        56       58     92       98        65    369
2        98       65     82       58        64    367
3        50       96     57       69        59    331
4        82       99     51       79        99    410
5        81       85     83       82        57    388
6        71       56     65       90        86    368
7        95       44     94       47        62    342
8        78       55     57       94        73    357
9        41       63     95       63        79    341
10       96       64     78       42        71    351


In [114]:
stu_names =  ["Erick Ondiwa", "Celine Patience", "James Wasonga", "Mark Emmanuel", "Felix Awere",
              "Purity Lukesh", "Shadrack Mutinda", "Mercy Achieng", "Kelvin Gichohi", "Clare Achieng"]
result.insert(0, "Names",stu_names)
print(result)

               Names  English  Physics  Maths  Biology  Computer  Total
1       Erick Ondiwa       56       58     92       98        65    369
2    Celine Patience       98       65     82       58        64    367
3      James Wasonga       50       96     57       69        59    331
4      Mark Emmanuel       82       99     51       79        99    410
5        Felix Awere       81       85     83       82        57    388
6      Purity Lukesh       71       56     65       90        86    368
7   Shadrack Mutinda       95       44     94       47        62    342
8      Mercy Achieng       78       55     57       94        73    357
9     Kelvin Gichohi       41       63     95       63        79    341
10     Clare Achieng       96       64     78       42        71    351


In [63]:
# stud_names = ["Erick Ondiwa", "Celine Patience", "James Wasonga", "Mark Emmanuel", "Felix Awere",
#              "Purity Lukesh", "Shadrack Mutinda", "Mercy Achieng", "Kelvin Gichohi", "Clare Achieng"]
# final_result['Names'] = stud_names
# print(final_result['Names'])

In [115]:
# Computing the mean of each subject
subject_mean = np.mean(marks, axis=0).reshape(1,5)
print(subject_mean)

[[74.8 68.5 75.4 72.2 71.5]]


In [9]:
# print(subject_mean[1])

In [103]:
print(np.sum(subject_mean))

351.8


In [116]:
# Assigning the mean row with index name 'Mean'
mean_row = pd.DataFrame(subject_mean, index=['Mean'], columns=subjects)
print(mean_row)
# mean_row = pd.DataFrame(
#     [{'English': subject_mean[0],
#       'Physics': subject_mean[1],
#       'Maths': subject_mean[2],
#       'Biology': subject_mean[3],
#       'Computer': subject_mean[4],
#       'Total': np.sum(subject_mean)}],
#     index=["Mean"]
# )

      English  Physics  Maths  Biology  Computer
Mean     74.8     68.5   75.4     72.2      71.5


In [117]:
# Using pd.concat to add the new row with custom index
final_result = pd.concat([result, mean_row])
print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     56.0     58.0   92.0     98.0      65.0  369.0
2      Celine Patience     98.0     65.0   82.0     58.0      64.0  367.0
3        James Wasonga     50.0     96.0   57.0     69.0      59.0  331.0
4        Mark Emmanuel     82.0     99.0   51.0     79.0      99.0  410.0
5          Felix Awere     81.0     85.0   83.0     82.0      57.0  388.0
6        Purity Lukesh     71.0     56.0   65.0     90.0      86.0  368.0
7     Shadrack Mutinda     95.0     44.0   94.0     47.0      62.0  342.0
8        Mercy Achieng     78.0     55.0   57.0     94.0      73.0  357.0
9       Kelvin Gichohi     41.0     63.0   95.0     63.0      79.0  341.0
10       Clare Achieng     96.0     64.0   78.0     42.0      71.0  351.0
Mean               NaN     74.8     68.5   75.4     72.2      71.5    NaN


In [118]:
# final_result[final_result['Total'] == 'NaN'] = np.sum(subject_mean)
final_result = final_result.fillna(np.sum(subject_mean))
print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     56.0     58.0   92.0     98.0      65.0  369.0
2      Celine Patience     98.0     65.0   82.0     58.0      64.0  367.0
3        James Wasonga     50.0     96.0   57.0     69.0      59.0  331.0
4        Mark Emmanuel     82.0     99.0   51.0     79.0      99.0  410.0
5          Felix Awere     81.0     85.0   83.0     82.0      57.0  388.0
6        Purity Lukesh     71.0     56.0   65.0     90.0      86.0  368.0
7     Shadrack Mutinda     95.0     44.0   94.0     47.0      62.0  342.0
8        Mercy Achieng     78.0     55.0   57.0     94.0      73.0  357.0
9       Kelvin Gichohi     41.0     63.0   95.0     63.0      79.0  341.0
10       Clare Achieng     96.0     64.0   78.0     42.0      71.0  351.0
Mean             362.4     74.8     68.5   75.4     72.2      71.5  362.4


In [119]:
high_achievers = result[result['Total'] >= 300]
print(high_achievers)

               Names  English  Physics  Maths  Biology  Computer  Total
1       Erick Ondiwa       56       58     92       98        65    369
2    Celine Patience       98       65     82       58        64    367
3      James Wasonga       50       96     57       69        59    331
4      Mark Emmanuel       82       99     51       79        99    410
5        Felix Awere       81       85     83       82        57    388
6      Purity Lukesh       71       56     65       90        86    368
7   Shadrack Mutinda       95       44     94       47        62    342
8      Mercy Achieng       78       55     57       94        73    357
9     Kelvin Gichohi       41       63     95       63        79    341
10     Clare Achieng       96       64     78       42        71    351


In [87]:
# final_result.loc['Mean'][0] = " "
# print(final_result)

In [120]:
print(result.sort_values('Total', ascending=False))

               Names  English  Physics  Maths  Biology  Computer  Total
4      Mark Emmanuel       82       99     51       79        99    410
5        Felix Awere       81       85     83       82        57    388
1       Erick Ondiwa       56       58     92       98        65    369
6      Purity Lukesh       71       56     65       90        86    368
2    Celine Patience       98       65     82       58        64    367
8      Mercy Achieng       78       55     57       94        73    357
10     Clare Achieng       96       64     78       42        71    351
7   Shadrack Mutinda       95       44     94       47        62    342
9     Kelvin Gichohi       41       63     95       63        79    341
3      James Wasonga       50       96     57       69        59    331


In [121]:
#  **** Position 1
first_pos = final_result.sort_values('Total').max()
print(first_pos)

TypeError: '>=' not supported between instances of 'str' and 'float'