In [2]:
import pandas as pd
import numpy as np

In [3]:
marks = np.random.randint(40, 100, (10,5))
print(marks)

[[86 58 65 56 79]
 [54 90 87 72 55]
 [72 84 63 91 52]
 [80 64 60 96 41]
 [85 89 97 40 85]
 [99 81 51 73 49]
 [93 98 47 80 70]
 [45 97 40 89 97]
 [96 89 93 48 41]
 [85 83 74 61 53]]


In [7]:
subjects = np.array(["English", "Physics", "Maths", "Biology", "Computer"])
result = pd.DataFrame(marks, columns=subjects, index=np.arange(1,11))
print(result)

    English  Physics  Maths  Biology  Computer
1        86       58     65       56        79
2        54       90     87       72        55
3        72       84     63       91        52
4        80       64     60       96        41
5        85       89     97       40        85
6        99       81     51       73        49
7        93       98     47       80        70
8        45       97     40       89        97
9        96       89     93       48        41
10       85       83     74       61        53


In [5]:
# Computing the total marks for each student
total_marks = np.sum(marks, axis=1)
print(total_marks)

[344 358 362 341 396 353 388 368 367 356]


In [12]:
result["Total"] = total_marks
print(result)

               Names  English  Physics  Maths  Biology  Computer  Total
1       Erick Ondiwa       86       58     65       56        79    344
2    Celine Patience       54       90     87       72        55    358
3      James Wasonga       72       84     63       91        52    362
4      Mark Emmanuel       80       64     60       96        41    341
5        Felix Awere       85       89     97       40        85    396
6   Morphine Achieng       99       81     51       73        49    353
7   Shadrack Mutinda       93       98     47       80        70    388
8      Mercy Achieng       45       97     40       89        97    368
9     Kelvin Gichohi       96       89     93       48        41    367
10     Clare Achieng       85       83     74       61        53    356


In [14]:
stu_names =  ["Erick Ondiwa", "Celine Patience", "James Wasonga", "Mark Emmanuel", "Felix Awere",
              "Morphine Achieng", "Shadrack Mutinda", "Mercy Achieng", "Kelvin Gichohi", "Clare Achieng"]
result.insert(0, "Names",stu_names)
print(result)

ValueError: cannot insert Names, already exists

In [63]:
# stud_names = ["Erick Ondiwa", "Celine Patience", "James Wasonga", "Mark Emmanuel", "Felix Awere",
#              "Purity Lukesh", "Shadrack Mutinda", "Mercy Achieng", "Kelvin Gichohi", "Clare Achieng"]
# final_result['Names'] = stud_names
# print(final_result['Names'])

In [15]:
# Computing the mean of each subject
subject_mean = np.mean(marks, axis=0).reshape(1,5)
print(subject_mean)

[[79.5 83.3 67.7 70.6 62.2]]


In [9]:
# print(subject_mean[1])

In [16]:
print(np.sum(subject_mean))

363.3


In [17]:
# Assigning the mean row with index name 'Mean'
mean_row = pd.DataFrame(subject_mean, index=['Mean'], columns=subjects)
print(mean_row)
# mean_row = pd.DataFrame(
#     [{'English': subject_mean[0],
#       'Physics': subject_mean[1],
#       'Maths': subject_mean[2],
#       'Biology': subject_mean[3],
#       'Computer': subject_mean[4],
#       'Total': np.sum(subject_mean)}],
#     index=["Mean"]
# )

      English  Physics  Maths  Biology  Computer
Mean     79.5     83.3   67.7     70.6      62.2


In [18]:
# Using pd.concat to add the new row with custom index
final_result = pd.concat([result, mean_row])
print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     86.0     58.0   65.0     56.0      79.0  344.0
2      Celine Patience     54.0     90.0   87.0     72.0      55.0  358.0
3        James Wasonga     72.0     84.0   63.0     91.0      52.0  362.0
4        Mark Emmanuel     80.0     64.0   60.0     96.0      41.0  341.0
5          Felix Awere     85.0     89.0   97.0     40.0      85.0  396.0
6     Morphine Achieng     99.0     81.0   51.0     73.0      49.0  353.0
7     Shadrack Mutinda     93.0     98.0   47.0     80.0      70.0  388.0
8        Mercy Achieng     45.0     97.0   40.0     89.0      97.0  368.0
9       Kelvin Gichohi     96.0     89.0   93.0     48.0      41.0  367.0
10       Clare Achieng     85.0     83.0   74.0     61.0      53.0  356.0
Mean               NaN     79.5     83.3   67.7     70.6      62.2    NaN


In [23]:
final_result.loc['Mean'][0] = 1
print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     86.0     58.0   65.0     56.0      79.0  344.0
2      Celine Patience     54.0     90.0   87.0     72.0      55.0  358.0
3        James Wasonga     72.0     84.0   63.0     91.0      52.0  362.0
4        Mark Emmanuel     80.0     64.0   60.0     96.0      41.0  341.0
5          Felix Awere     85.0     89.0   97.0     40.0      85.0  396.0
6     Morphine Achieng     99.0     81.0   51.0     73.0      49.0  353.0
7     Shadrack Mutinda     93.0     98.0   47.0     80.0      70.0  388.0
8        Mercy Achieng     45.0     97.0   40.0     89.0      97.0  368.0
9       Kelvin Gichohi     96.0     89.0   93.0     48.0      41.0  367.0
10       Clare Achieng     85.0     83.0   74.0     61.0      53.0  356.0
Mean             363.3     79.5     83.3   67.7     70.6      62.2  363.3


C:\Users\ErickOndiwa\AppData\Local\Temp\ipykernel_12736\2163823210.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_result.loc['Mean'][0] = 1
C:\Users\ErickOndiwa\AppData\Local\Temp\ipykernel_12736\2163823210.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  final_result.loc['Mean'][0] = 1


In [19]:
# final_result[final_result['Total'] == 'NaN'] = np.sum(subject_mean)
final_result = final_result.fillna(np.sum(subject_mean))
print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     86.0     58.0   65.0     56.0      79.0  344.0
2      Celine Patience     54.0     90.0   87.0     72.0      55.0  358.0
3        James Wasonga     72.0     84.0   63.0     91.0      52.0  362.0
4        Mark Emmanuel     80.0     64.0   60.0     96.0      41.0  341.0
5          Felix Awere     85.0     89.0   97.0     40.0      85.0  396.0
6     Morphine Achieng     99.0     81.0   51.0     73.0      49.0  353.0
7     Shadrack Mutinda     93.0     98.0   47.0     80.0      70.0  388.0
8        Mercy Achieng     45.0     97.0   40.0     89.0      97.0  368.0
9       Kelvin Gichohi     96.0     89.0   93.0     48.0      41.0  367.0
10       Clare Achieng     85.0     83.0   74.0     61.0      53.0  356.0
Mean             363.3     79.5     83.3   67.7     70.6      62.2  363.3


In [119]:
high_achievers = result[result['Total'] >= 300]
print(high_achievers)

               Names  English  Physics  Maths  Biology  Computer  Total
1       Erick Ondiwa       56       58     92       98        65    369
2    Celine Patience       98       65     82       58        64    367
3      James Wasonga       50       96     57       69        59    331
4      Mark Emmanuel       82       99     51       79        99    410
5        Felix Awere       81       85     83       82        57    388
6      Purity Lukesh       71       56     65       90        86    368
7   Shadrack Mutinda       95       44     94       47        62    342
8      Mercy Achieng       78       55     57       94        73    357
9     Kelvin Gichohi       41       63     95       63        79    341
10     Clare Achieng       96       64     78       42        71    351


In [87]:
# final_result.loc['Mean'][0] = " "
# print(final_result)

In [120]:
print(result.sort_values('Total', ascending=False))

               Names  English  Physics  Maths  Biology  Computer  Total
4      Mark Emmanuel       82       99     51       79        99    410
5        Felix Awere       81       85     83       82        57    388
1       Erick Ondiwa       56       58     92       98        65    369
6      Purity Lukesh       71       56     65       90        86    368
2    Celine Patience       98       65     82       58        64    367
8      Mercy Achieng       78       55     57       94        73    357
10     Clare Achieng       96       64     78       42        71    351
7   Shadrack Mutinda       95       44     94       47        62    342
9     Kelvin Gichohi       41       63     95       63        79    341
3      James Wasonga       50       96     57       69        59    331


In [25]:
#  **** Position 1
# first_pos = final_result.sort_values('Total').max()
# print(first_pos)