In [72]:
import pandas as pd
import numpy as np

In [73]:
marks = np.random.randint(40, 100, (10,5))
print(marks)

[[65 61 89 53 84]
 [72 87 76 83 93]
 [55 97 52 64 71]
 [47 43 93 65 49]
 [77 89 61 69 47]
 [41 64 63 55 56]
 [75 40 56 52 40]
 [99 45 89 93 65]
 [62 66 64 66 91]
 [63 43 53 61 46]]


In [74]:
subjects = np.array(["English", "Physics", "Maths", "Biology", "Computer"])
result = pd.DataFrame(marks, columns=subjects, index=np.arange(1,11))
print(result)

    English  Physics  Maths  Biology  Computer
1        65       61     89       53        84
2        72       87     76       83        93
3        55       97     52       64        71
4        47       43     93       65        49
5        77       89     61       69        47
6        41       64     63       55        56
7        75       40     56       52        40
8        99       45     89       93        65
9        62       66     64       66        91
10       63       43     53       61        46


In [75]:
# Computing the total marks for each student
total_marks = np.sum(marks, axis=1)
print(total_marks)

[352 411 339 297 343 279 263 391 349 266]


In [76]:
result["Total"] = total_marks
print(result)

    English  Physics  Maths  Biology  Computer  Total
1        65       61     89       53        84    352
2        72       87     76       83        93    411
3        55       97     52       64        71    339
4        47       43     93       65        49    297
5        77       89     61       69        47    343
6        41       64     63       55        56    279
7        75       40     56       52        40    263
8        99       45     89       93        65    391
9        62       66     64       66        91    349
10       63       43     53       61        46    266


In [77]:
stu_names =  ["Erick Ondiwa", "Celine Patience", "James Wasonga", "Mark Emmanuel", "Felix Awere",
              "Morphine Achieng", "Shadrack Mutinda", "Mercy Achieng", "Kelvin Gichohi", "Clare Achieng"]
result.insert(0, "Names",stu_names)
print(result)

               Names  English  Physics  Maths  Biology  Computer  Total
1       Erick Ondiwa       65       61     89       53        84    352
2    Celine Patience       72       87     76       83        93    411
3      James Wasonga       55       97     52       64        71    339
4      Mark Emmanuel       47       43     93       65        49    297
5        Felix Awere       77       89     61       69        47    343
6   Morphine Achieng       41       64     63       55        56    279
7   Shadrack Mutinda       75       40     56       52        40    263
8      Mercy Achieng       99       45     89       93        65    391
9     Kelvin Gichohi       62       66     64       66        91    349
10     Clare Achieng       63       43     53       61        46    266


In [63]:
# stud_names = ["Erick Ondiwa", "Celine Patience", "James Wasonga", "Mark Emmanuel", "Felix Awere",
#              "Purity Lukesh", "Shadrack Mutinda", "Mercy Achieng", "Kelvin Gichohi", "Clare Achieng"]
# final_result['Names'] = stud_names
# print(final_result['Names'])

In [78]:
# Computing the mean of each subject
subject_mean = np.mean(marks, axis=0).reshape(1,5)
print(subject_mean)

[[65.6 63.5 69.6 66.1 64.2]]


In [9]:
# print(subject_mean[1])

In [79]:
print(np.sum(subject_mean))

328.99999999999994


In [80]:
# Assigning the mean row with index name 'Mean'
mean_row = pd.DataFrame(subject_mean, index=['Mean'], columns=subjects)
print(mean_row)
# mean_row = pd.DataFrame(
#     [{'English': subject_mean[0],
#       'Physics': subject_mean[1],
#       'Maths': subject_mean[2],
#       'Biology': subject_mean[3],
#       'Computer': subject_mean[4],
#       'Total': np.sum(subject_mean)}],
#     index=["Mean"]
# )

      English  Physics  Maths  Biology  Computer
Mean     65.6     63.5   69.6     66.1      64.2


In [82]:
mean_row['Total'] = np.sum(subject_mean)

In [83]:
# Using pd.concat to add the new row with custom index
final_result = pd.concat([result, mean_row])
print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     65.0     61.0   89.0     53.0      84.0  352.0
2      Celine Patience     72.0     87.0   76.0     83.0      93.0  411.0
3        James Wasonga     55.0     97.0   52.0     64.0      71.0  339.0
4        Mark Emmanuel     47.0     43.0   93.0     65.0      49.0  297.0
5          Felix Awere     77.0     89.0   61.0     69.0      47.0  343.0
6     Morphine Achieng     41.0     64.0   63.0     55.0      56.0  279.0
7     Shadrack Mutinda     75.0     40.0   56.0     52.0      40.0  263.0
8        Mercy Achieng     99.0     45.0   89.0     93.0      65.0  391.0
9       Kelvin Gichohi     62.0     66.0   64.0     66.0      91.0  349.0
10       Clare Achieng     63.0     43.0   53.0     61.0      46.0  266.0
Mean               NaN     65.6     63.5   69.6     66.1      64.2  329.0


In [84]:
replaced_name = final_result.replace({final_result.loc["Mean","Names"] : " "})
print(replaced_name)

                 Names  English  Physics  Maths  Biology  Computer  Total
1         Erick Ondiwa     65.0     61.0   89.0     53.0      84.0  352.0
2      Celine Patience     72.0     87.0   76.0     83.0      93.0  411.0
3        James Wasonga     55.0     97.0   52.0     64.0      71.0  339.0
4        Mark Emmanuel     47.0     43.0   93.0     65.0      49.0  297.0
5          Felix Awere     77.0     89.0   61.0     69.0      47.0  343.0
6     Morphine Achieng     41.0     64.0   63.0     55.0      56.0  279.0
7     Shadrack Mutinda     75.0     40.0   56.0     52.0      40.0  263.0
8        Mercy Achieng     99.0     45.0   89.0     93.0      65.0  391.0
9       Kelvin Gichohi     62.0     66.0   64.0     66.0      91.0  349.0
10       Clare Achieng     63.0     43.0   53.0     61.0      46.0  266.0
Mean                       65.6     63.5   69.6     66.1      64.2  329.0


In [45]:
# # final_result[final_result['Total'] == 'NaN'] = np.sum(subject_mean)
# final_result = final_result.fillna(np.sum(subject_mean))
# print(final_result)

In [85]:
high_achievers = result[result['Total'] >= 300]
print(high_achievers)

             Names  English  Physics  Maths  Biology  Computer  Total
1     Erick Ondiwa       65       61     89       53        84    352
2  Celine Patience       72       87     76       83        93    411
3    James Wasonga       55       97     52       64        71    339
5      Felix Awere       77       89     61       69        47    343
8    Mercy Achieng       99       45     89       93        65    391
9   Kelvin Gichohi       62       66     64       66        91    349


In [87]:
# final_result.loc['Mean'][0] = " "
# print(final_result)

In [86]:
print(result.sort_values('Total', ascending=False))

               Names  English  Physics  Maths  Biology  Computer  Total
2    Celine Patience       72       87     76       83        93    411
8      Mercy Achieng       99       45     89       93        65    391
1       Erick Ondiwa       65       61     89       53        84    352
9     Kelvin Gichohi       62       66     64       66        91    349
5        Felix Awere       77       89     61       69        47    343
3      James Wasonga       55       97     52       64        71    339
4      Mark Emmanuel       47       43     93       65        49    297
6   Morphine Achieng       41       64     63       55        56    279
10     Clare Achieng       63       43     53       61        46    266
7   Shadrack Mutinda       75       40     56       52        40    263


In [89]:
final_result["Comment"] = final_result['Total'].apply(lambda x: "Excellent" if x >= 400 else "Credit" if x >= 380 else "Good" if x >= 350 else "Fair" if x >= 300 else "Pass")

print(final_result)

                 Names  English  Physics  Maths  Biology  Computer  Total  \
1         Erick Ondiwa     65.0     61.0   89.0     53.0      84.0  352.0   
2      Celine Patience     72.0     87.0   76.0     83.0      93.0  411.0   
3        James Wasonga     55.0     97.0   52.0     64.0      71.0  339.0   
4        Mark Emmanuel     47.0     43.0   93.0     65.0      49.0  297.0   
5          Felix Awere     77.0     89.0   61.0     69.0      47.0  343.0   
6     Morphine Achieng     41.0     64.0   63.0     55.0      56.0  279.0   
7     Shadrack Mutinda     75.0     40.0   56.0     52.0      40.0  263.0   
8        Mercy Achieng     99.0     45.0   89.0     93.0      65.0  391.0   
9       Kelvin Gichohi     62.0     66.0   64.0     66.0      91.0  349.0   
10       Clare Achieng     63.0     43.0   53.0     61.0      46.0  266.0   
Mean               NaN     65.6     63.5   69.6     66.1      64.2  329.0   

        Comment  
1          Good  
2     Excellent  
3          Fair  
4  

In [47]:
#  **** Position 1
first_pos = final_result.nlargest(1, "Total")
# print(first_pos)

          Names  English  Physics  Maths  Biology  Computer  Total
1  Erick Ondiwa     98.0     86.0   75.0     95.0      80.0  434.0
