In [2]:
import numpy as np

The Basics

In [4]:
ints = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ints)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Get shape - The shape attribute returns the dimensions of the array as a tuple. 
# It tells you how many elements exist along each axis
ints.shape

(3, 3)

In [6]:
# Get dimensions
ints.ndim

2

In [7]:
# Get type - The dtype (data type) attribute indicates the type of elements stored in the array, like int32, float64, etc.
# The itemsize is directly related to the dtype since the size of each element depends on its data type
ints.dtype

dtype('int64')

In [9]:
# Get size - The size attribute in NumPy returns the total number of elements in the array. 
# It is the product of the array's shape

ints.size

9

In [11]:
# Get item size - The itemsize attribute returns the size (in bytes) of each individual element in the array.
# This depends on the data type (dtype) of the array 

ints.itemsize

8

In [12]:
# Get the Memory size consumed - The nbytes attribute returns the total memory consumed by the entire array, in bytes. 
# It is calculated as nbytes = size * itemsize.

ints.nbytes

72

Accessing/ Changing Specific Elements, rows, columns

1. Accessing Specific Elements - To access specific elements in a NumPy array, you use indexing

For a 1D Array

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

# Access the first element
print(arr[0])  # Output: 10

# Access the last element
print(arr[-1])  # Output: 50


For a 2D Array - For multi-dimensional arrays, you provide an index for each axis (row and column in a 2D array)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Access element at row 0, column 2
print(arr[0, 2])  # Output: 3

# Access element at row 1, column 1
print(arr[1, 1])  # Output: 5


2. Changing Specific Elements

For a 1D array

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Change the value of the first element
arr[0] = 100
print(arr)  # Output: [100, 20, 30, 40, 50]


For a 2D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Change element at row 0, column 1
arr[0, 1] = 20
print(arr)  # Output: [[ 1, 20, 3], [ 4, 5, 6]]


Accessing Rows - To access entire rows of a 2D array, you only need to specify the row index.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the first row
print(arr[0, :])  # Output: [1, 2, 3]

# Access the second row
print(arr[1, :])  # Output: [4, 5, 6]


Changing Rows - You can replace an entire row by assigning a new array to that row.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Change the first row
arr[0, :] = [10, 20, 30]
print(arr)
# Output: [[10, 20, 30], [ 4,  5,  6], [ 7,  8,  9]]


Accessing Columns - To access an entire column, specify the column index and use : to indicate all rows.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the first column
print(arr[:, 0])  # Output: [1, 4, 7]

# Access the second column
print(arr[:, 1])  # Output: [2, 5, 8]


Changing Columns - Similar to rows, you can replace an entire column by assigning a new array to that column.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Change the second column
arr[:, 1] = [20, 50, 80]
print(arr)
# Output: [[ 1, 20,  3], [ 4, 50,  6], [ 7, 80,  9]]


7. Accessing Subarrays (Slicing)
Slicing allows you to access specific ranges of rows, columns, or elements from the array. You specify the start and end index of the slice for each axis.

For a 1D array

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Access elements from index 1 to 4 (exclusive)
print(arr[1:4])  # Output: [20, 30, 40]

# Access every other element
print(arr[::2])  # Output: [10, 30, 50]


For a 2D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access a subarray (rows 0 to 1, columns 0 to 1)
print(arr[0:2, 0:2])  # Output: [[1, 2], [4, 5]]

# Access every other row and column
print(arr[::2, ::2])  # Output: [[1, 3], [7, 9]]


8. Changing Subarrays
You can also modify specific subarrays by assigning new values to slices.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Change the top-left 2x2 subarray
arr[0:2, 0:2] = [[10, 20], [40, 50]]
print(arr)
# Output: [[10, 20,  3], [40, 50,  6], [ 7,  8,  9]]


9. Fancy Indexing (Indexing with Arrays)
Fancy indexing allows you to access or modify elements using lists or arrays of indices.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Access elements at indices 0, 2, and 4
print(arr[[0, 2, 4]])  # Output: [10, 30, 50]

# Modify elements at indices 1 and 3
arr[[1, 3]] = [200, 400]
print(arr)  # Output: [ 10, 200,  30, 400,  50]


For 2D arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access elements at row indices 0 and 2, and column indices 1 and 2
print(arr[[0, 2], [1, 2]])  # Output: [2, 9]


10. Boolean Indexing
You can use boolean arrays to access or modify elements that satisfy certain conditions.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Access elements greater than 30
print(arr[arr > 30])  # Output: [40, 50]

# Modify elements less than or equal to 30
arr[arr <= 30] = 100
print(arr)  # Output: [100, 100, 100, 40, 50]


For 2D arrays

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access elements greater than 4
print(arr[arr > 4])  # Output: [5, 6, 7, 8, 9]


11. Using np.where for Conditional Access
np.where() allows you to conditionally access or modify elements.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Access indices where elements are greater than 30
indices = np.where(arr > 30)
print(indices)  # Output: (array([3, 4]),)

# Replace elements less than or equal to 30 with 0
arr[np.where(arr <= 30)] = 0
print(arr)  # Output: [ 0,  0,  0, 40, 50]
