Initializing Different Types of arrays

1. Creating Arrays from Lists or Tuples
The simplest way to create a NumPy array is from a Python list or tuple using np.array().

In [1]:
import numpy as np

# From a list
arr = np.array([1, 2, 3])
print(arr)  # Output: [1 2 3]

# From a tuple
arr_tuple = np.array((4, 5, 6))
print(arr_tuple)  # Output: [4 5 6]


[1 2 3]
[4 5 6]


2. Arrays Filled with Zeros
You can create arrays filled with zeros using np.zeros().
This is useful for initializing an array with all values as zero, often used in machine learning models or matrix computations.

In [7]:
# 1D array of 5 zeros
arr = np.zeros(5)
print(arr)  # Output: [0. 0. 0. 0. 0.]

# 2D array of shape (3, 4) filled with zeros
arr_2d = np.zeros((3,4))
print(arr_2d)
# Output: [[0. 0. 0. 0.]
#          [0. 0. 0. 0.]
#          [0. 0. 0. 0.]]

matrices = np.zeros((3, 4, 2)) # This array will have 3 blocks(matrices), each block to contain 4 rows with 2 elements each.
print(matrices)


[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


3. Arrays Filled with Ones
Use np.ones() to create arrays filled with ones, which is often
helpful in cases like initializing weights or matrices.

In [11]:
# 1D array of 5 ones
arr = np.ones(5)
# print(arr)  # Output: [1. 1. 1. 1. 1.]

# 2D array of shape (2, 3) filled with ones
arr_2d = np.ones((2, 3))
# print(arr_2d)
# Output: [[1. 1. 1.]
#          [1. 1. 1.]]

fancy_arr = np.zeros((2, 3, 4, 5))#2groups,each group contains 3matrices,each matrix has 4rows,and each row contains 5elements
print(fancy_arr)


[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


4. Arrays Filled with a Specific Value
To create an array filled with any specific value, you can use np.full(). This is useful when you want a constant matrix.

In [ ]:
# 2D array of shape (3, 3) filled with the value 7
arr = np.full((3, 3), 7)
print(arr)
# Output: [[7 7 7]
#          [7 7 7]
#          [7 7 7]]


5. Identity Matrix
An identity matrix has ones on the leading diagonal and zeros elsewhere.
 You can create an identity matrix using np.eye().

In [ ]:
# 3x3 identity matrix
arr = np.eye(3)
print(arr)
# Output: [[1. 0. 0.]
#          [0. 1. 0.]
#          [0. 0. 1.]]


6. Uninitialized Arrays:
NumPy also allows you to create arrays without initializing the values using np.empty().
The values are unpredictable because they are just whatever data happens to be in memory at the time.
This can be faster if you intend to overwrite all elements later.

In [ ]:
# 2D array of shape (3, 3) uninitialized
arr = np.empty((3, 3))
print(arr)
# Output: unpredictable values (e.g., [[0.  0.  0. ]
#                                      [1.5 2.1 3.3]
#                                      [0.  0.  0. ]])


7. Range of Numbers
To create arrays with numbers in a specific range, you can use np.arange(), which works similarly to Python’s range() function but returns an array.

In [ ]:
# Array with values from 0 to 9
arr = np.arange(10)
print(arr)  # Output: [0 1 2 3 4 5 6 7 8 9]

# Array with values from 1 to 10, step size of 2
arr_step = np.arange(1, 10, 2)
print(arr_step)  # Output: [1 3 5 7 9]


8. Evenly Spaced Numbers (linspace):
Use np.linspace() to create an array of evenly spaced numbers over a specified range.
You specify the start, stop, and how many points you want.

In [ ]:
# 5 numbers evenly spaced between 0 and 1
arr = np.linspace(0, 1, 5)
print(arr)  # Output: [0.   0.25 0.5  0.75 1.  ]


9. Random Numbers:
NumPy provides functions for initializing arrays with random numbers.
These can be used for simulations, initializing model weights, etc.

a. Random numbers from a uniform distribution (np.random.rand())
Generates random numbers between 0 and 1 from a uniform distribution.

In [ ]:
# 1D array of 5 random numbers between 0 and 1
arr = np.random.rand(5)
print(arr)  # Output: Random values like [0.7744, 0.2453, 0.5923, ...]

# 2D array of shape (3, 3) of random numbers between 0 and 1
arr_2d = np.random.rand(3, 3)
print(arr_2d)
# Output: Random values like [[0.372, 0.489, 0.012],
#                             [0.674, 0.982, 0.735],
#                             [0.215, 0.631, 0.123]]


b. Random integers (np.random.randint())
Generates random integers between a specified low and high value.

In [9]:
# 1D array of 5 random integers between 10 and 20
arr = np.random.randint(10, 20, 5)
print(arr)  # Output: Random integers like [11, 15, 13, 19, 10]

# 2D array of shape (2, 3) of random integers between 0 and 100
arr_2d = np.random.randint(0, 100, (5, 3))
print(arr_2d)
# Output: Random integers like [[22, 73, 41], [98, 33, 51]]


[13 10 11 15 10]
[[65 26 84]
 [11  4 66]
 [45 50 29]
 [41 48 62]
 [ 6 77 39]]


c. Random numbers from a normal (Gaussian) distribution (np.random.randn())
Generates numbers from a standard normal distribution (mean = 0, standard deviation = 1).

In [ ]:
# 1D array of 5 random numbers from a normal distribution
arr = np.random.randn(5)
print(arr)  # Output: Random values like [-0.223, 1.678, -1.234, ...]

# 2D array of shape (3, 3) of random numbers from a normal distribution
arr_2d = np.random.randn(3, 3)
print(arr_2d)
# Output: Random values like [[ 0.224, -1.564,  0.789],
#                             [-0.879,  1.458,  0.123],
#                             [-1.324,  0.956, -0.123]]


10. Initializing Arrays for Common Patterns:
NumPy also provides functions to generate arrays for common mathematical patterns or matrices.

a. Diagonal matrix (np.diag())
Creates an array with the specified diagonal values.

In [ ]:
# Diagonal matrix with diagonal values 1, 2, 3
arr = np.diag([1, 2, 3])
print(arr)
# Output: [[1 0 0]
#          [0 2 0]
#          [0 0 3]]


b. Triangular matrix (np.tri())
Creates a lower triangular matrix (with ones below and on the diagonal).

In [ ]:
# Lower triangular matrix of shape (3, 3)
arr = np.tri(3)
print(arr)
# Output: [[1. 0. 0.]
#          [1. 1. 0.]
#          [1. 1. 1.]]


In [19]:
ones = np.ones((5,5))
print(puzzle)

zeros = np.zeros((3,3))
zeros[1,1] = 9
print(zeros)

ones[1:4, 1:4] = zeros
print(ones)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
