In [2]:
import numpy as np

The Basics

In [4]:
ints = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ints)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Get shape - The shape attribute returns the dimensions of the array as a tuple. 
# It tells you how many elements exist along each axis
ints.shape

(3, 3)

In [6]:
# Get dimensions
ints.ndim

2

In [7]:
# Get type - The dtype (data type) attribute indicates the type of elements stored in the array, like int32, float64, etc.
# The itemsize is directly related to the dtype since the size of each element depends on its data type
ints.dtype

dtype('int64')

In [9]:
# Get size - The size attribute in NumPy returns the total number of elements in the array. 
# It is the product of the array's shape

ints.size

9

In [11]:
# Get size - The itemsize attribute returns the size (in bytes) of each individual element in the array.
# This depends on the data type (dtype) of the array 

ints.itemsize

8

In [12]:
# Get the Memory size consumed - The nbytes attribute returns the total memory consumed by the entire array, in bytes. 
# It is calculated as nbytes = size * itemsize.

ints.nbytes

72