In [1]:
import pandas as pd
import numpy as np

In [25]:
marks = np.random.randint(30, 100, (11,5))
print(marks)

[[75 79 65 52 68]
 [34 83 66 50 44]
 [85 55 48 48 69]
 [50 61 52 89 71]
 [76 44 87 32 50]
 [80 52 53 99 63]
 [34 47 62 68 70]
 [72 91 90 97 95]
 [44 64 47 42 49]
 [30 68 98 92 70]
 [99 38 42 82 67]]


In [30]:
subjects = np.array(["English", "Physics", "Maths", "Biology", "Computer"])
result = pd.DataFrame(marks, columns=subjects, index=np.arange(1,12))
print(result)

    English  Physics  Maths  Biology  Computer
1        75       79     65       52        68
2        34       83     66       50        44
3        85       55     48       48        69
4        50       61     52       89        71
5        76       44     87       32        50
6        80       52     53       99        63
7        34       47     62       68        70
8        72       91     90       97        95
9        44       64     47       42        49
10       30       68     98       92        70
11       99       38     42       82        67


In [17]:
# Computing the total marks for each student
total_marks = np.sum(marks, axis=1)
print(total_marks)

[277 302 334 272 302 292 316 302 346 323]


In [18]:
result["Total"] = total_marks
print(result)

    English  Physics  Maths  Biology  Computer  Total
1        53       67     62       50        45    277
2        43       63     55       57        84    302
3        82       47     65       53        87    334
4        46       49     78       67        32    272
5        51       65     85       53        48    302
6        67       61     57       42        65    292
7        77       57     32       84        66    316
8        93       49     57       32        71    302
9        60       41     81       71        93    346
10       37       93     32       87        74    323


In [34]:
# Computing the mean of each subject
subject_mean = np.mean(marks, axis=0)
print(subject_mean)

[61.72727273 62.         64.54545455 68.27272727 65.09090909]


In [36]:
# Assigning the mean row to the result
marks[11:] = subject_mean
print(result)

    English  Physics  Maths  Biology  Computer
1        75       79     65       52        68
2        34       83     66       50        44
3        85       55     48       48        69
4        50       61     52       89        71
5        76       44     87       32        50
6        80       52     53       99        63
7        34       47     62       68        70
8        72       91     90       97        95
9        44       64     47       42        49
10       30       68     98       92        70
11       99       38     42       82        67


In [29]:
coffee_sale = pd.read_csv('./warmup-data/coffee.csv')
print(coffee_sale.tail())

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35


In [23]:
# coffee_sale.describe()

In [24]:
# print(coffe_sale['Units Sold'])

In [26]:
monday_sale = coffee_sale[coffee_sale['Day'] == 'Monday']
print(monday_sale)

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15


In [27]:
espresso_sale = coffee_sale[coffee_sale['Coffee Type'] == 'Espresso']
print(espresso_sale)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45


In [20]:
high_price = coffee_sale[coffee_sale['Units Sold'] > 30]
print(high_price)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35


In [21]:
# Creating a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [24, 27, 22]
}
df = pd.DataFrame(data, index=["a", "b", "c"])
print(df)

      Name  Age
a    Alice   24
b      Bob   27
c  Charlie   22


In [22]:
# Using .loc to access data by label
row_b = df.loc["b"]  # Access row with label "b"
print(row_b)

Name    Bob
Age      27
Name: b, dtype: object


In [ ]:
age_of_bob = df.loc["b", "Age"]  # Access "Age" of the row with label "b"
print(age_of_bob)