In [34]:
import pandas as pd
import numpy as np

In [41]:
marks = np.random.randint(30, 100, (10,5))
print(marks)

[[44 74 84 45 92]
 [80 59 55 48 77]
 [32 98 37 74 76]
 [33 91 80 37 54]
 [43 83 45 75 78]
 [48 85 82 36 58]
 [31 62 32 95 42]
 [39 45 83 52 61]
 [80 98 45 40 35]
 [93 79 74 96 95]]


In [66]:
subjects = np.array(["English", "Physics", "Maths", "Biology", "Computer"])
result = pd.DataFrame(marks, columns=subjects, index=np.arange(1,11))
print(result)

    English  Physics  Maths  Biology  Computer
1        44       74     84       45        92
2        80       59     55       48        77
3        32       98     37       74        76
4        33       91     80       37        54
5        43       83     45       75        78
6        48       85     82       36        58
7        31       62     32       95        42
8        39       45     83       52        61
9        80       98     45       40        35
10       93       79     74       96        95


In [45]:
# Computing the total marks for each student
total_marks = np.sum(marks, axis=1)
print(total_marks)

[339 319 317 295 324 309 262 280 298 437]


In [67]:
result["Total"] = total_marks
print(result)

    English  Physics  Maths  Biology  Computer  Total
1        44       74     84       45        92    339
2        80       59     55       48        77    319
3        32       98     37       74        76    317
4        33       91     80       37        54    295
5        43       83     45       75        78    324
6        48       85     82       36        58    309
7        31       62     32       95        42    262
8        39       45     83       52        61    280
9        80       98     45       40        35    298
10       93       79     74       96        95    437


In [47]:
# Computing the mean of each subject
subject_mean = np.mean(marks, axis=0)
print(subject_mean)

[52.3 77.4 61.7 59.8 66.8]


In [54]:
print(subject_mean[1])

77.4


In [55]:
print(np.sum(subject_mean))

318.0


In [63]:
# Assigning the mean row with index name 'Mean'
new_row = pd.DataFrame(
    [{'English': subject_mean[0],
      'Physics': subject_mean[1],
      'Maths': subject_mean[2],
      'Biology': subject_mean[3],
      'Computer': subject_mean[4],
      'Total': np.sum(subject_mean)}],
    index=["Mean"]
)

In [68]:
# Using pd.concat to add the new row with custom index
final_result = pd.concat([result, new_row])
print(final_result)

      English  Physics  Maths  Biology  Computer  Total
1        44.0     74.0   84.0     45.0      92.0  339.0
2        80.0     59.0   55.0     48.0      77.0  319.0
3        32.0     98.0   37.0     74.0      76.0  317.0
4        33.0     91.0   80.0     37.0      54.0  295.0
5        43.0     83.0   45.0     75.0      78.0  324.0
6        48.0     85.0   82.0     36.0      58.0  309.0
7        31.0     62.0   32.0     95.0      42.0  262.0
8        39.0     45.0   83.0     52.0      61.0  280.0
9        80.0     98.0   45.0     40.0      35.0  298.0
10       93.0     79.0   74.0     96.0      95.0  437.0
Mean     52.3     77.4   61.7     59.8      66.8  318.0


In [29]:
coffee_sale = pd.read_csv('./warmup-data/coffee.csv')
print(coffee_sale.tail())

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35


In [23]:
# coffee_sale.describe()

In [24]:
# print(coffe_sale['Units Sold'])

In [26]:
monday_sale = coffee_sale[coffee_sale['Day'] == 'Monday']
print(monday_sale)

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15


In [27]:
espresso_sale = coffee_sale[coffee_sale['Coffee Type'] == 'Espresso']
print(espresso_sale)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
2     Tuesday    Espresso          30
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45


In [20]:
high_price = coffee_sale[coffee_sale['Units Sold'] > 30]
print(high_price)

          Day Coffee Type  Units Sold
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35


In [30]:
eith_sale = coffee_sale.loc[8]
print(eith_sale)

Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object


In [21]:
# Creating a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [24, 27, 22]
}
df = pd.DataFrame(data, index=["a", "b", "c"])
print(df)

      Name  Age
a    Alice   24
b      Bob   27
c  Charlie   22


In [22]:
# Using .loc to access data by label
row_b = df.loc["b"]  # Access row with label "b"
print(row_b)

Name    Bob
Age      27
Name: b, dtype: object


In [ ]:
age_of_bob = df.loc["b", "Age"]  # Access "Age" of the row with label "b"
print(age_of_bob)