In [10]:
import numpy as np

In [11]:
import math

In [12]:
ints = np.array([1, 2, 3, 4, 5])

In [14]:
squares = ints**2
print(squares)

[ 1  4  9 16 25]


In [15]:
cubes = np.power(ints, 3)
print(cubes)

[  1   8  27  64 125]


In [17]:
mul = ints * 2 # This multiplies all the contents of an array by 2
print(mul)

[ 2  4  6  8 10]


In [18]:
div = ints / 2 # This divides all the contents of an array by 2
print(div)

[0.5 1.  1.5 2.  2.5]


In [19]:
addition = np.sum(ints)
print(addition)

15


# Other mathematical functions

In [20]:
_sin = np.sin(ints) # This prints te sine of every element in the array
print(_sin)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [21]:
_cos = np.cos(ints) # This prints te cosine of every element in the array
print(_cos)

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
