In [1]:
import numpy as np
from numpy import matrix

In [3]:
v1 = np.arange(0,6)
v2 =  np.arange(2,5)
mul = v1 * 2
print(mul)

[ 0  2  4  6  8 10]


In [5]:
add = v1 + v2
print(add) # operands could not be broadcast together with shapes (7,) (4,) 

ValueError: operands could not be broadcast together with shapes (6,) (3,) 

In [7]:
mat1 = v1.reshape(2,3)
print(mat1)

[[0 1 2]
 [3 4 5]]


In [25]:
elem2 = np.arange(0,2)
print(elem2)

[0 1]


In [26]:
elem3 = np.arange(0,3)
print(elem3)

[0 1 2]


In [27]:
mult1 = mat1 * elem2 # You can't multiply 3 columns by 2 columns
print(mult)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [28]:
mult2 = mat1 * elem3 # It is possible to multiply 3 columns by 3 columns
print(mult2)

[[ 0  1  4]
 [ 0  4 10]]


In [29]:
mult3 = elem3 * mat1
print(mult3)

[[ 0  1  4]
 [ 0  4 10]]


In [9]:
mat2 = np.arange(4,13).reshape(3,3) # Same no of columns, hence can be multiplied
print(mat2)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
mult4 = mat1 * mat2 # Same no of columns(3), hence can be multiplied
print(mult4)

[[ 0  5 12]
 [21 32 45]]


In [32]:
mat3 = np.arange(0,8).reshape(2,4)
print(mat3)

[[0 1 2 3]
 [4 5 6 7]]


In [33]:
mult5 = mat1 * mat3 # Different columns, 3 and 4, hence can't be multiplied
print(mult5)

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [11]:

mat1T = matrix(mat1).T
print(mat1T)

[[0 3]
 [1 4]
 [2 5]]


In [43]:
elem2T = matrix(elem2).T
print(elem2T)

[[0]
 [1]]


In [47]:
mul6 = mat1 * elem2T
print(mul6)

ValueError: shapes (2,3) and (2,1) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
mul7 = mat1 * mat1T
print(mul7)

[[ 5 14]
 [14 50]]


In [50]:
squ_mat = np.arange(1,10).reshape(3,3)
print(squ_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
vec1 = np.arange(1,4)
print(vec1)
vec1T = matrix(vec1).T
print(vec1T)

[1 2 3]
[[1]
 [2]
 [3]]


In [62]:
mul8 = squ_mat * vec1T # 3by3 * 3by1 = 3by1
print(mul8)

[[14]
 [32]
 [50]]


In [61]:
mul9 = mat1 * vec1T # 2by3 * 3by1 = 2by1
print(mul9)

[[ 8]
 [26]]


In [63]:
mul10 = vec1T * mat1 # 3by1 * 2by3 = 2by1 
print(mul10)

ValueError: shapes (3,1) and (2,3) not aligned: 1 (dim 1) != 2 (dim 0)

In [65]:
print(mat1 * mat1)
print(np.dot(mat1, mat1)) # 2by3 matrix can't be multiplied with the dot() due to a mismatch in the row * column multiplicatio

[[ 0  1  4]
 [ 9 16 25]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [67]:
square_matx = np.arange(1,5).reshape(2,2)
print(square_matx)

[[1 2]
 [3 4]]


In [68]:
print(square_matx * square_matx)
print(np.dot(square_matx, square_matx)) # A square matrix can be multiplied with the dot()

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [6]:
vector1 = np.arange(0,3)
print(vector1)
vector2 = np.arange(3,7) 
print(vector2)

[0 1 2]
[3 4 5 6]


In [7]:
print(vector1 * vector2)
print(np.dot(vector1,vector2))

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [10]:
m1 = np.arange(1, 7).reshape(2,3)
print(m1)

[[1 2 3]
 [4 5 6]]


In [11]:
print(m1.ravel())

[1 2 3 4 5 6]


In [14]:
print(m1.T)
m2 = m1.T
print(m2)
print(m2.ravel())

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


In [15]:
m3 = m1.flatten()
print(m3)

[1 2 3 4 5 6]


In [25]:
matx1 = np.arange(1,5).reshape(2,2)
print(matx1)

[[1 2]
 [3 4]]


In [18]:
print(np.repeat(matx, 2))

[1 1 2 2 3 3 4 4]


In [19]:
print(np.tile(matx, 2))

[1 2 3 4 1 2 3 4]


In [ ]:
matx2 = np.arange(5,11)
print(matx2)

In [33]:
mat1C =np.concatenate((matx1, matx1))
print(mat1C)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [37]:
print(np.vstack(matx1))
print(np.hstack(matx1))

[[1 2]
 [3 4]]
[1 2 3 4]
