In [3]:
import numpy as np

# Generate student indexes from 1 to 10
stu_indexes = np.arange(1, 11)
print(stu_indexes)


[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Generate random marks for 10 students in 5 subjects
stu_marks = np.random.randint(40, 100, size=(10, 5))
print(stu_marks)

# Print student indexes and their corresponding marks
for stu_index, stu_mark in zip(stu_indexes, stu_marks):
    print(f"Student {stu_index}: Marks {stu_mark}")

[[43 67 84 49 51]
 [73 85 95 49 94]
 [49 54 46 64 58]
 [69 63 49 65 92]
 [78 81 55 46 58]
 [98 90 55 60 99]
 [84 55 91 66 47]
 [62 46 64 75 96]
 [92 64 60 68 80]
 [59 91 79 97 68]]
Student 1: Marks [43 67 84 49 51]
Student 2: Marks [73 85 95 49 94]
Student 3: Marks [49 54 46 64 58]
Student 4: Marks [69 63 49 65 92]
Student 5: Marks [78 81 55 46 58]
Student 6: Marks [98 90 55 60 99]
Student 7: Marks [84 55 91 66 47]
Student 8: Marks [62 46 64 75 96]
Student 9: Marks [92 64 60 68 80]
Student 10: Marks [59 91 79 97 68]


In [5]:
# Calculate total marks for each student
total_marks = np.sum(stu_marks, axis=1)

# Print total marks for each student
for stu_index, total_mark in zip(stu_indexes, total_marks):
    print(f"Student {stu_index}: Total Marks = {total_mark}")

Student 1: Total Marks = 286
Student 2: Total Marks = 372
Student 3: Total Marks = 399
Student 4: Total Marks = 402
Student 5: Total Marks = 315
Student 6: Total Marks = 362
Student 7: Total Marks = 322
Student 8: Total Marks = 345
Student 9: Total Marks = 341
Student 10: Total Marks = 378


In [6]:
# Compute and print the mean marks for each subject
mean_subject_marks = np.mean(stu_marks, axis=0)
print("\nMean marks for each subject:")
for i, mean_mark in enumerate(mean_subject_marks, start=1):
    print(f"Subject {i}: Mean = {mean_mark:.2f}")


Mean marks for each subject:
Subject 1: Mean = 73.80
Subject 2: Mean = 76.10
Subject 3: Mean = 65.50
Subject 4: Mean = 70.90
Subject 5: Mean = 65.90


In [7]:
# Compute graduation units for each student (best 4 subjects)
graduation_units = np.sort(stu_marks, axis=1)[:, -4:]  # Get the best 4 marks
print("\nGraduation units (best 4 subjects) for each student:")
for stu_index, units in zip(stu_indexes, graduation_units):
    print(f"Student {stu_index}: Best 4 Marks = {units}, Total of Best 4 = {np.sum(units)}")


Graduation units (best 4 subjects) for each student:
Student 1: Best 4 Marks = [46 48 61 88], Total of Best 4 = 243
Student 2: Best 4 Marks = [71 74 80 93], Total of Best 4 = 318
Student 3: Best 4 Marks = [75 86 90 93], Total of Best 4 = 344
Student 4: Best 4 Marks = [76 80 83 89], Total of Best 4 = 328
Student 5: Best 4 Marks = [49 70 75 79], Total of Best 4 = 273
Student 6: Best 4 Marks = [51 84 91 91], Total of Best 4 = 317
Student 7: Best 4 Marks = [52 65 74 81], Total of Best 4 = 272
Student 8: Best 4 Marks = [59 69 74 99], Total of Best 4 = 301
Student 9: Best 4 Marks = [58 60 81 93], Total of Best 4 = 292
Student 10: Best 4 Marks = [59 88 91 93], Total of Best 4 = 331


In [47]:
stu_dict = {}
for stu_index, stu_mark in zip(stu_indexes, stu_marks):
    print(f"Student {stu_index}: Marks {stu_mark}")
    stu_dict[int(stu_index)] = stu_mark.tolist()  # Convert NumPy array to list for each student

# Print the resulting dictionary
print("\nStudent Dictionary:")
print(stu_dict)

Student 1: Marks [43 67 84 49 51]
Student 2: Marks [73 85 95 49 94]
Student 3: Marks [49 54 46 64 58]
Student 4: Marks [69 63 49 65 92]
Student 5: Marks [78 81 55 46 58]
Student 6: Marks [98 90 55 60 99]
Student 7: Marks [84 55 91 66 47]
Student 8: Marks [62 46 64 75 96]
Student 9: Marks [92 64 60 68 80]
Student 10: Marks [59 91 79 97 68]

Student Dictionary:
{1: [43, 67, 84, 49, 51], 2: [73, 85, 95, 49, 94], 3: [49, 54, 46, 64, 58], 4: [69, 63, 49, 65, 92], 5: [78, 81, 55, 46, 58], 6: [98, 90, 55, 60, 99], 7: [84, 55, 91, 66, 47], 8: [62, 46, 64, 75, 96], 9: [92, 64, 60, 68, 80], 10: [59, 91, 79, 97, 68]}


In [52]:
# Create a dictionary to track marks for each subject
subject_dict = {}

# Loop over each subject (columns in the NumPy array)
for subject_index in range(stu_marks.shape[1]):
    subject_dict[f"Subject {subject_index + 1}"] = stu_marks[:, subject_index].tolist()

# Print the subject-wise marks
print("\nMarks corresponding to each subject:")
for subject, marks in subject_dict.items():
    print(f"{subject}: {marks}")


Marks corresponding to each subject:
Subject 1: [43, 73, 49, 69, 78, 98, 84, 62, 92, 59]
Subject 2: [67, 85, 54, 63, 81, 90, 55, 46, 64, 91]
Subject 3: [84, 95, 46, 49, 55, 55, 91, 64, 60, 79]
Subject 4: [49, 49, 64, 65, 46, 60, 66, 75, 68, 97]
Subject 5: [51, 94, 58, 92, 58, 99, 47, 96, 80, 68]


In [ ]:
#Two classes, student and course.
#Every course has  name and code,
#and every student has a name, regno and courses and a method registration that accepst parameter, course

In [18]:
class Course:
    def __init__(self, course_name, code):
        self.name = name
        self.code = code
course1 = Course("Ai", "CCS311")
course2 = Course("Ml", "CCS321")
course3 = Course("Algorithms", "CCS311")
course4 = Course("Automata", "CCS311")
course5 = Course("Ai", "CCS311")
print(course1.name)
print(course1.code)

Ai
CCS311


In [24]:
class Student:
    self.courses = []
    def __init__(self, name, regNo):
        self.name = name
        self.regNo = regNo 

    def stu_reg(self, course):
        self.course = self.courses
        #self.course = Course
        self.courses.append(course)

stu1 = Student("Erick", "CCS/00081/022")
print(stu1.stu_reg())

NameError: name 'self' is not defined