## 🔹 4. Encoding Categorical Variables
Machine learning models require numerical data, so we must convert categorical variables into numbers.

## 🔸 One-Hot Encoding

In [5]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [7]:
# Sample categorical data
data = np.array([['Red'], ['Blue'], ['Green'], ['Red'], ['Blue']])

In [9]:
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(data)

print("One-Hot Encoded Data:\n", encoded_data)

One-Hot Encoded Data:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


## 📌 Other techniques:

Label Encoding – Assigns each category a unique number
Ordinal Encoding – Useful for ordered categories (e.g., Low, Medium, High)
